### ISSUE TITLE
implement templates

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-back#11]

**Comment by albjeremias** [comment]
missing tests!

**Comment by albjeremias** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/26681446/132690215-05233772-b41b-4ef7-9c12-80d130f448cf.png">

**Comment by watchoutfreedom** [comment]
yes that field was confusing, I thought we can have a type (offer, need, exchange), and a template (that includes a potential name), so the example should have both fields. Also customizing templates in network admin panel is going to have two layers, one is the fields you add to the button, and other is the global fields that you enable/disable for the network. Maybe here's we need another missing for the network itself

**Comment by watchoutfreedom** [comment]
In order to simplify let's keep the templates as it is fro now. I just modified buttons so they're the same and match the networks setup

<img width="1475" alt="Captura de pantalla 2021-09-10 a las 20 12 35" src="https://user-images.githubusercontent.com/23015314/132892134-d66e55b7-c473-4a3f-af8e-d48fa605074c.png">

**Comment by albjeremias** [comment]
I merged https://github.com/helpbuttons/hb-back/pull/14
so the template became defined like here:
https://github.com/helpbuttons/hb-back/blob/develop/src/__tests__/controllers/template-button.controller.test.ts#L32
you can also check the models.

I'll close this issue.. feel free to open it again. or to create a new one to improve the feature! ;)
